"""Write the multi-GPU SLURM training script without variable expansion."""
D = chr(36)
path = '/scratch/gpfs/HENDERSON/zs7353/ssm_ttt/scripts/run_32kp_c1c2_multigpu.sh'
with open(path, 'w') as f:
    f.write('#!/bin/bash\n')
    f.write('#SBATCH --job-name=32kp_C1C2\n')
    f.write('#SBATCH --account=henderson\n')
    f.write('#SBATCH --time=59:00\n')
    f.write('#SBATCH --nodes=1\n#SBATCH --ntasks=1\n')
    f.write('#SBATCH --cpus-per-task=16\n')
    f.write('#SBATCH --mem=128G\n')
    f.write('#SBATCH --gres=gpu:a100:2\n')
    f.write('#SBATCH --signal=B:USR1@120\n')
    f.write('#SBATCH --output=/scratch/gpfs/HENDERSON/zs7353/ssm_ttt/scripts/32kp_c1c2_%j.out\n\n')
    f.write('module load anaconda3/2025.12\n')
    f.write('conda activate /scratch/gpfs/HENDERSON/zs7353/envs/ssm_ttt\n')
    f.write('module load cudatoolkit/12.6\n')
    f.write('export CUDA_HOME=/usr/local/cuda-12.6\n')
    f.write('export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True\n\n')
    f.write('cd /scratch/gpfs/HENDERSON/zs7353/ssm_ttt\n\n')
    f.write('echo "Node: ' + D + '(hostname)"\n')
    f.write('echo "Started: ' + D + '(date)"\n\n')
    f.write('CUDA_VISIBLE_DEVICES=0 python train.py --config configs/stage1_32k_C1.yaml &\n')
    f.write('PID_C1=' + D + '!\n')
    f.write('CUDA_VISIBLE_DEVICES=1 python train.py --config configs/stage1_32k_C2.yaml &\n')
    f.write('PID_C2=' + D + '!\n\n')
    f.write('echo "C1='+D+'PID_C1 C2='+D+'PID_C2"\n\n')
    f.write('forward_signal() {\n')
    f.write('    kill -USR1 '+D+'PID_C1 2>/dev/null\n')
    f.write('    kill -USR1 '+D+'PID_C2 2>/dev/null\n')
    f.write('}\ntrap forward_signal USR1 TERM INT\n\n')
    f.write('while kill -0 '+D+'PID_C1 2>/dev/null || kill -0 '+D+'PID_C2 2>/dev/null; do\n')
    f.write('    wait '+D+'PID_C1 '+D+'PID_C2 2>/dev/null\ndone\n\n')
    f.write('echo "Both done: '+D+'(date)"\n')
print("Written to", path)
